[model]
name="stepfun/step-3.5-flash:free"
temperature = 0

[[hooks]]
name='test_before_tool'
trigger='before_tool'
command='python3 ./scripts/test_tool.py'

[[hooks]]
name='test_before_agent'
trigger='before_agent'
command='python3 ./scripts/test_tool.py'

[mcp_servers.filesystem]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", "/Users/hp/Desktop/claudekode", "/tmp"]

[mcp_servers.filesystem2]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem222222222222", "/Users/hp/Desktop/claudekode", "/tmp"]
